# Generated by Django 4.0.4 on 2022-06-09 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='main/static/main/img/kitigawa.png', upload_to='img/', verbose_name='Картинка')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('rating', models.IntegerField(choices=[(1, '1/10'), (2, '2/10'), (3, '3/10'), (4, '4/10'), (5, '5/10'), (6, '6/10'), (7, '7/10'), (8, '8/10'), (9, '9/10'), (10, '10/10')], verbose_name='Оценка')),
            ],
        ),
    ]
